# Site settings
title: Sass Guidelines
description: "an opinionated styleguide for writing sane, maintainable and scalable Sass"
baseurl: "/sass-guidelines"
url: "http://sass-guidelin.es"
twitter_username: taupecat
github_username:  RP3Agency

# Build settings
markdown: kramdown
